### ISSUE TITLE
edutopia embedding uses obsolete code

### ISSUE THREAD

**Issue by townxelliot** [Whiteknight/mediawiki-embedvideo#10]
edutopia embedding doesn't work, as the HTML code appears to be incorrect.

It just needs updating to newer HTML embed code, as in the attached patch. (Not knowing much about Flash embedding, it could be that this can be reduced further.)

Fixed by this commit:
http://github.com/townxelliot/mediawiki-embedvideo/commit/b3c123e71bced4a492d906a331d7bfc92be23452

**Comment by Whiteknight** [comment]
I have merged in this patch, but haven't been able to verify whether it works or not. Do you have a test case that I can try out?

**Comment by townxelliot** [comment]
Try:

{{#ev:edutopia|619249870001}}

**Comment by Whiteknight** [comment]
Yes, you're right. That video works perfectly. Thanks.
