### ISSUE TITLE
Notice triggered when looking for 'extern' key

### ISSUE THREAD

**Issue by townxelliot** [Whiteknight/mediawiki-embedvideo#11]
If a service definition doesn't have an extern key, you get a Notice triggered when the EmbedVideo extension tries to display a video from that service.

Fixed by this commit:
http://github.com/townxelliot/mediawiki-embedvideo/commit/e478098656055549c75368a973ac6640cbbf1710

**Comment by Whiteknight** [comment]
Merged. Thanks!
