### ISSUE TITLE
Support for Vimeo

### ISSUE THREAD

**Issue by amig** [Whiteknight/mediawiki-embedvideo#15]
Although Vimeo is supposed to be supported, it is not.

The following should be added to the $wgEmbedVideoServiceList array (either in the EmbedVideo.Services.php or LocalSettings.php files):

```
'vimeo' => array('extern' => '<iframe src="http://player.vimeo.com/video/$2" width="$3" frameborder="0"></iframe>')
```

:)

**Comment by Whiteknight** [comment]
The current code doesn't work? I'll have to do some tests on it. Can you give me an example video to test with? Thanks

**Comment by amig** [comment]
You can test with any vimeo video (e.g., 7411858).

**Comment by Whiteknight** [comment]
I just tested it, and Vimeo support works just fine. I'm on MediaWiki 1.16.0, and viewing in FireFox 3.6.12.

What browser are you running where you see these problems?

**Comment by amig** [comment]
I just downloaded the file again and now it includes the vimeo code.  In the file I downloaded on Sunday (Whiteknight-mediawiki-embedvideo-v1.0-0-g2be8876.tar.gz) this was missing.  Both files are version 1.0!

BTW, some other stuff, as well, was changed in the current file compared to the one I downloaded on Sunday.

**Comment by Whiteknight** [comment]
Hmm... that's weird. I'll have to look at those download files and make sure they are valid. I haven't updated that file since I created it, so I feel like it should be the same every time. Thanks for the notice. I'm closing this ticket.
