### ISSUE TITLE
sevenload is broken

### ISSUE THREAD

**Issue by ceiermann** [Whiteknight/mediawiki-embedvideo#16]
Hi there,
embedding sevenload videos doesn't work anymore.
See by yourself: http://jimbojw.com/wiki/index.php?title=EmbedVideo_Extension
I would be happy if you could fix that. I believe this is the only video hoster without limits when it comes to lenght.

Thanks guys!

**Comment by hollosch** [comment]
Hi,
i can confirm this issue. Maybe there is a problem with separate country-subdomains, eg. en, de, .... ?

thanks!

**Comment by hollosch** [comment]
Any news about this issue ?

**Comment by ceiermann** [comment]
I accidentally pressed "comment and close" intstead of "comment". I have no idea how to change the status so I reopened the issue here: https://github.com/Whiteknight/mediawiki-embedvideo/issues/issue/18
