### ISSUE TITLE
Playback size error: YoutubeHD

### ISSUE THREAD

**Issue by sirreal** [Whiteknight/mediawiki-embedvideo#22]
The default size calculated for HD YouTube videos will leave black bars on the sides of the video (if it is 16:9 video).
This is because it doesn't account for the 15px control bar at the bottom. It is easily solved by changing the ratio for youtubehd in the EmbedVideo.Services.php file to 72/43.

```
    'youtubehd' => array(
        'url' => 'http://www.youtube.com/v/$1&ap=%2526fmt%3D22&fs=1',
        'default_width' => 720,
        'default_ratio' => 16/9       // <-----change this to 72/43
    )
```

**Comment by Whiteknight** [comment]
Thanks for the report (and sorry I'm getting to it so late). I'll do some testing on this and hopefully have something to push after the holiday.

**Comment by sirreal** [comment]
OK, thanks!
