### ISSUE TITLE
Group usage permissions

### ISSUE THREAD

**Issue by hseljenes** [Whiteknight/mediawiki-embedvideo#24]
I couldn't find anything in the documentation and skimming the code didn't turn anything up for this request:

Is there a way to allow define permissions for this extensions use?

Something like $wgGroupPermissions['user']['embedvideo'] = false;

I only want to allow certain groups to embed videos.

**Comment by Whiteknight** [comment]
There is no way in the code to do this. I don't think it's possible.
We could set up permissions to prevent people from _watching_ videos,
but we cannot prevent people from adding new videos. The video
embedding tag is just text saved to the DB, and anybody with edit
permissions can edit the page. There's no way for the software to
parse it out and determine if you've added a new tag or edited a page
with an existing tag.

Sorry,

--Andrew Whitworth

On Tue, Feb 14, 2012 at 12:02 PM, hseljenes
reply@reply.github.com
wrote:

**Comment by hseljenes** [comment]
That's what I was worried of. Guess we'll investigate some other routes. Thanks!
