### ISSUE TITLE
does not work in fresh 1.20.2 mediawiki install

### ISSUE THREAD

**Issue by splaisan** [Whiteknight/mediawiki-embedvideo#27]
when the conflg file is active in LocalSettings.php, my wiki does not load anymore.
commenting the line and all is back
Any idea welcome
thanks

**Comment by Whiteknight** [comment]
I haven't tried 1.20.x yet. I'll try to spin up a test of that and see what happens

**Comment by splaisan** [comment]
appears I have a general issue with installing additional extension.
searching hard but not finding what is wrong. The first two installed but now I cannot add any more
Yours probably works OK.

Stephane

Stéphane Plaisance | stephane.plaisance@gmail.com
